cursor            #9fcaff
cursor_text_color #003259

foreground            #e1e2e8
background            #0c0e12
selection_foreground  #1e3248
selection_background  #b4c8e4
url_color             #b4c8e4

#: black 000000 767676
color0  #111417
color8  #323539
#: red cc0403 f2201f
color1  #102d49
color9  #2c7bc6
#: green 19cb00 23fd00
color2  #b4c8e4
color10 #d2e4ff
#: yellow cecb00 fffd00
color3  #edb2fa
color11 #fbd7ff
#: blue 0d73cc 1a8fff
color4  #00497e
color12 #9fcaff
#: magenta cb1ed1 fd28ff
color5  #35485f
color13 #b4c8e4
#: cyan 0dcdcd 14ffff
color6  #633372
color14 #edb2fa
#: white dddddd ffffff
color7  #c1c7d1
color15 #e1e2e8

mark1_foreground #001d36
mark1_background #d2e4ff
mark2_foreground #071d32
mark2_background #d2e4ff
mark3_foreground #330143
mark3_background #fbd7ff

active_tab_foreground #003259
active_tab_background #9fcaff
inactive_tab_foreground #ffffff
inactive_tab_background #2b67a1

active_border_color #9fcaff
inactive_border_color #003259
# bell_border_color #ff5a00