cursor            #eab5ee
cursor_text_color #48204f

foreground            #eadfe6
background            #110d11
selection_foreground  #3b2b3c
selection_background  #d7bfd5
url_color             #d7bfd5

#: black 000000 767676
color0  #171217
color8  #393338
#: red cc0403 f2201f
color1  #153072
color9  #4371dd
#: green 19cb00 23fd00
color2  #d7bfd5
color10 #f4dbf2
#: yellow cecb00 fffd00
color3  #f6b8ae
color11 #ffdad5
#: blue 0d73cc 1a8fff
color4  #613767
color12 #eab5ee
#: magenta cb1ed1 fd28ff
color5  #524153
color13 #d7bfd5
#: cyan 0dcdcd 14ffff
color6  #673b35
color14 #f6b8ae
#: white dddddd ffffff
color7  #d0c3cc
color15 #eadfe6

mark1_foreground #300938
mark1_background #ffd6ff
mark2_foreground #251726
mark2_background #f4dbf2
mark3_foreground #33110d
mark3_background #ffdad5

active_tab_foreground #48204f
active_tab_background #eab5ee
inactive_tab_foreground #ffd6ff
inactive_tab_background #613767

active_border_color #eab5ee
inactive_border_color #48204f
# bell_border_color #ff5a00