$image = /home/shahmeer/.dotfiles/.config/hypr/wallpapers/wallpaper7.jpg

$background = rgba(111417ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(2e3035ff)

$inverse_primary = rgba(23619bff)

$inverse_surface = rgba(e1e2e8ff)

$on_background = rgba(e1e2e8ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(003259ff)

$on_primary_container = rgba(ffffffff)

$on_primary_fixed = rgba(001d36ff)

$on_primary_fixed_variant = rgba(00497eff)

$on_secondary = rgba(1e3248ff)

$on_secondary_container = rgba(cee2feff)

$on_secondary_fixed = rgba(071d32ff)

$on_secondary_fixed_variant = rgba(35485fff)

$on_surface = rgba(e1e2e8ff)

$on_surface_variant = rgba(c1c7d1ff)

$on_tertiary = rgba(4a1b59ff)

$on_tertiary_container = rgba(ffffffff)

$on_tertiary_fixed = rgba(330143ff)

$on_tertiary_fixed_variant = rgba(633372ff)

$outline = rgba(8b919bff)

$outline_variant = rgba(414750ff)

$primary = rgba(9fcaffff)

$primary_container = rgba(2b67a1ff)

$primary_fixed = rgba(d2e4ffff)

$primary_fixed_dim = rgba(9fcaffff)

$scrim = rgba(000000ff)

$secondary = rgba(b4c8e4ff)

$secondary_container = rgba(35485fff)

$secondary_fixed = rgba(d2e4ffff)

$secondary_fixed_dim = rgba(b4c8e4ff)

$shadow = rgba(000000ff)

$source_color = rgba(2b67a1ff)

$surface = rgba(111417ff)

$surface_bright = rgba(37393eff)

$surface_container = rgba(1d2024ff)

$surface_container_high = rgba(282a2eff)

$surface_container_highest = rgba(323539ff)

$surface_container_low = rgba(191c20ff)

$surface_container_lowest = rgba(0c0e12ff)

$surface_dim = rgba(111417ff)

$surface_tint = rgba(9fcaffff)

$surface_variant = rgba(414750ff)

$tertiary = rgba(edb2faff)

$tertiary_container = rgba(845192ff)

$tertiary_fixed = rgba(fbd7ffff)

$tertiary_fixed_dim = rgba(edb2faff)
