
source = colors.conf 

$font = JetBrainsMono Nerd Font
$font_bold = JetBrainsMono Nerd Font bold

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 5
}

input-field {
    monitor =
    size = 15%, 5%
    outline_thickness = 4
    inner_color = $on_surface_variant

    outer_color =  rgba(0, 0, 0, 0.0) # no fill
    check_color =  rgba(0, 0, 0, 0.0) # no fill
    fail_color = $error_container 120deg

    font_color = $on_secondary
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = 
    fail_text = 
    
    dots_size = 0.25
    dots_spacing = 0.3

    position = -10, -150
    halign = center
    valign = center
}



# TIME
label {
    monitor =
    text = $TIME 
    font_size = 90
    color = $primary
    font_family = $font_bold

    position = -37.7%, -25%
    halign = right
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 25
    color = $primary
    font_family = $font_bold

    position = -35%, -45%
    halign = right
    valign = top
}

label {
    monitor =
    text = Hi there, $USER
    font_size = 15
    color = $primary
    font_family = $font_bold

    position = -12, -70
    halign = center
    valign = center
}

